config/routes.rb
Rails.application.routes.draw do
  root  'users#index'
  resources :users

  resources :nuts do
    resources :comments
  end


  post '/users/login', to: 'users#login'
  get '/users/:id/destroy', to: 'users#destroy', :as => "sign_out"
  post '/users', to: 'users#create', :as => 'sign_in'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :content
  belongs_to :nut
  belongs_to :user
end

app/models/nut.rb
class Nut < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  validates_presence_of :url
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :nuts
  has_many :comments

  has_secure_password
  validates :email, format: {with: /[-0-9a-zA-Z.+_]+@[-0-9a-zA-Z.+_]+\.[a-zA-Z]{2,}/}
  validates_presence_of :email, :first_name, :password, :password_confirmation, :username
  validates_uniqueness_of :email, :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

end

app/controllers/nuts_controller.rb
class NutsController < ApplicationController
  include UsersHelper
  include NutsHelper

  def index
    if current_user
      @user = User.find(session[:user_id])
      @nuts = Nut.all.reverse
    else
      redirect_to :root
    end
  end

  def new
    @user = current_user
  end

  def show
    @user = User.find(session[:user_id])
  end

  def create
    uploaded_picture = params[:picture]
    filename = Rails.root.join('public', 'uploads', uploaded_picture.original_filename)
    File.open(filename, 'wb') do |file|
      file.write(uploaded_picture.read)
    end
    image = Cloudinary::Uploader.upload(filename)
    @nut = Nut.new(url: [image["secure_url"]], user_id: current_user.id, content: params[:content])
    if @nut.save
      FileUtils.rm_rf(filename)
      redirect_to nuts_path
    else
      redirect_to user_path
    end
  end

  def edit
    @nut = Nut.find(params[:id])
  end

  def update
    @nut = Nut.find(params[:id])

    if @nut.update(content: params[:content])
      redirect_to nuts_path
    else
      render 'edit'
    end
  end

  def destroy
    current_user
    @nut = Nut.find(params[:id])
    @nut.destroy

    redirect_to :back
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
include UsersHelper
  def index
    if current_user
      redirect_to nuts_path
    end
  end

  def login
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      # redirect_to user_path(@user), flash: {notice: "Successful log in!"}
      redirect_to nuts_path, flash: {notice: "Successful log in!"}
    else
      redirect_to users_path, flash: {notice: 'Invalid Credentials!' }
    end
  end

  def create
    @user = User.new(user_params(params))
    if @user.save
      session[:user_id] = @user.id
      # redirect_to user_path(@user), flash: {notice: 'Successful log in!'}
      redirect_to nuts_path, flash: {notice: "Successful log in!"}
    else
      redirect_to new_user_path, flash: {notice: 'Failed'}
    end
  end

  def show
    if !current_user
      redirect_to :root
    end
    @user = User.find(params[:id])
  end

  def destroy
    session.clear
    redirect_to :root
  end

 private

  def user_params(params)
    params.require(:user).permit(:first_name, :username, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/nuts_helper.rb
module NutsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nutshell</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Unkempt:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <nav>

  <nav>
  <% if current_user %>
    <div class="left-nav">
      <button><%= link_to current_user.username, current_user %></button>
      <button><%= link_to 'Home', :root  %></button>
    </div>
    <div class="right-nav">
      <button><%= link_to 'Create!', new_nut_path %></button>
      <button><%= link_to 'Sign Out', sign_out_path(current_user) %></button>
    </div>
  <% else %>
    <div class="left-nav">
      <button><%= link_to 'Sign Up!', new_user_path %></button>
      <button><%= link_to 'Sign In!', root_path %></button>
    </div>
  <% end %>
  </nav>

    </nav>
    <div class="main">

<%= yield %>
    </div>
</body>
</html>

app/views/nuts/edit.html.erb
<h1>In a Nutshell...</h1>
<%= form_tag({action: :update}, multipart: true, method: :patch) do %>
  <!-- Backlog -->
  <%#= file_field_tag :picture %>
  <%= text_area_tag :content %>
  <div class='text-center'>
    <%= submit_tag('Upload') %>
  </div>
<% end %>

app/views/nuts/index.html.erb
<%= cloudinary_js_config %>
<h1>Welcome <%= @user.first_name %></h1>
<h2>Nutshells:</h2>

<% @nuts.each do |nut| %>

  <h2><%= link_to nut.user.first_name, user_path(nut.user_id) %></h2> <br>
  <div class="nut_image">
  <% nut.url.each do |image| %>
    <%= image_tag image, {height: 128} %>
  <% end %>
  </div>
  <br>
<% end %>

app/views/nuts/new.html.erb
<h1>In a Nutshell...</h1>
<%= form_tag({action: :create}, multipart: true) do %>
  <%= file_field_tag :picture %>
  <%= text_area_tag :content %>
  <div class='text-center'>
    <%= submit_tag('Upload') %>
  </div>
<% end %>

app/views/nuts/show.html.erb
Your nutshell has been successfully deleted.

<%= link_to 'go back', :back %>

app/views/users/_sign_in.html.erb
<%= notice %>

<%= form_for :user,  url: {action: "login"} do |f| %>

    <%= f.label :username, "username" %><br />
    <%= f.text_field :username %><br>

    <%= f.label :password %><br />
    <%= f.password_field :password  %><br>

    <div class="text-center">
      <%= f.submit "Log In", :class => "login"%>
    </div>




<% end %>

app/views/users/_sign_up.html.erb
<div class="cover-pic">
    <div class="cover-form">

        <span class="logo">Nutshell</span> <br>
        <span class="nut_logo"><%= image_tag "acorn-dark-green.png" %></span>

<%= flash[:notice] %>
    <%= form_for :user,  url: {action: "create"} do |f| %>

    <%= f.label :first_name, "First name" %><br />
    <%= f.text_field :first_name %><br>

    <%= f.label :username, "username" %><br />
    <%= f.text_field :username  %><br>

    <%= f.label :email, "Email" %><br />
    <%= f.text_field :email  %><br>

    <%= f.label :password %><br />
    <%= f.password_field :password   %><br>

    <%= f.label :password_confirmation, "Confirm password" %><br />
    <%= f.password_field :password_confirmation  %><br>

    <div class="text-center">
      <%= f.submit "Sign me up!", :class => "login"%>
    </div>

<% end %>
</div>
</div>

app/views/users/index.html.erb
<div class="cover-pic">
<div class="cover-form">

<span class="logo">Nutshell</span> <br>
<span class="nut_logo"><%= image_tag "acorn-dark-green.png" %></span> <br>


<%= render "sign_in" %>
<button class="login">
  <%= link_to 'Sign Up!', new_user_path %> <br>
</button>



</div>

</div>

app/views/users/new.html.erb
<%= render "sign_up" %>

app/views/users/show.html.erb
<%= javascript_include_tag :defaults %>
<h1><%= @user.username %></h1>
<h3><%= @user.first_name %>'s profile</h3>
<h1>Bio:</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem eligendi architecto possimus cumque, commodi, molestiae ullam reiciendis fuga dolorem dolor sequi accusantium neque, eius eos, qui quos tempore voluptatum omnis.</p>
<% @user.nuts.each do |nut| %>
<% if @user == current_user %>
  <%= link_to 'Edit', edit_nut_path(nut) %>
  <%= link_to 'Destroy', nut_path(nut),
                    method: :delete %>
<% end %>
  <%= time_ago_in_words(nut.updated_at) %> ago. <br>
  <% nut.url.each do |image| %>
    <%= image_tag image, {height: 128} %>
  <% end %> <br>
  <b><%= @user.first_name %>'s day, in a nutshell. </b> <br>
  <p><%= nut.content %></p> <br>
<% end %>